### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by sebakerckhof** [peerlibrary/meteor-related#7]
Can I have multiple related queries in one publish function?

So, will this work?:
```js
Meteor.publish('relatedTest', function(id) {
  check(groupId,String);
  this.related(function (user) {
      return Posts.find({_id: {$in: user.follows}});
  },
  Meteor.users.find(this.userId, {fields: {follows: 1}})
  );

  this.related(function (user) {
    return Addresses.find({_id: {$in: user.addresses}});
  },
  Meteor.users.find(this.userId, {fields: {addresses: 1}})
  );
 }
});
```

And can one related query return multiple cursors?

So, will this work:
```js
Meteor.publish('relatedTest', function(id) {
  check(groupId,String);
  this.related(function (user) {
      return [
         Posts.find({_id: {$in: user.follows}});
         Comments.find({post: {$in: user.follows}});
       ];
  },
  Meteor.users.find(this.userId, {fields: {follows: 1}})
  );
 }
});
```

**Comment by mitar** [comment]
Hm, the second thing should work. But I see I do not have a test for it. Feel free to make a pull request.

The first thing might work, but I have never tried it. In the worst case you can make two publish endpoints and just subscribe to both. But maybe make a test and a pull request as well. :-)

**Comment by sebakerckhof** [comment]
Okay, I'll test some things out.

I could use multiple publish functions, but I do some quite complex en expensive access control functions (which I omitted in the examples above). So it would be more efficient if I only need to do these once.

**Comment by mitar** [comment]
Why not making the first one:

```javascript
Meteor.publish('relatedTest', function(id) {
  check(groupId,String);
  this.related(function (user) {
      return [
        Posts.find({_id: {$in: user.follows}}),
        Addresses.find({_id: {$in: user.addresses}})
      ]
  },
  Meteor.users.find(this.userId, {fields: {follows: 1}})
  );
 }
});
```

**Comment by mitar** [comment]
Hm, but you are afraid that it would run too many times unnecessary?

**Comment by sebakerckhof** [comment]
Yes, that is indeed why i wanted to split it up. I haven't had the time to look into this further but will do so soon. Thanks for the feedback

**Comment by mitar** [comment]
Yea, but that might also be possibly premature optimization. Meteor remembers which documents you published, so if you publish the same, nothing will happen, nothing will go to the client again. So maybe a bit higher CPU, but nothing extra would go over the wire.

**Comment by mitar** [comment]
Added tests. It works as expected. :-)

**Comment by mitar** [comment]
We made a different API, a better one, which uses full reactivity: https://github.com/peerlibrary/meteor-reactive-publish
